import { Router } from "express";
import { userRoutes } from "./userRoutes.mjs";
import { authRoutes } from "./authRoutes.mjs";
import { isAuthenticate } from "../middleware/userMiddleware.mjs";
import { productRoutes } from "./productRoutes.mjs";
export const router = Router();
// router.use("/users", isAuthenticate, userRoutes);
router.use("/users", userRoutes);
router.use("/auth", authRoutes);
router.use("/products", isAuthenticate, productRoutes);
